#!/usr/bin/env bash
#Ejecutar en bash

# Verifica si se pasó un argumento
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Realiza el ping 5 veces
ping -c 5 "$1"
