#!/usr/bin/env bash
#Se debe ejecutar con bash

# Esperar 1 segundo antes de intentar modificar el archivo (ajustar según sea necesario)
sleep 1

# Eliminar las líneas si existen
sudo sed -i '/127.0.0.2 localhost/d' /etc/hosts
sudo sed -i '/8.8.8.8 facebook.com/d' /etc/hosts

# Agregar las nuevas entradas
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
